### ISSUE TITLE
error

### ISSUE THREAD

**Issue by basco-johnkevin** [766b/wmapi_sign#1]
I'm getting this error when I use the WmpapiSign function:

`OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error`

Any idea why?

I already set the correct values for:

- customerID
- secretKey
- method
- url

I'm executing the function like this:

`WmpapiSign('GET', 'https://api-gateway.walmart.com/v3/inventory?shipNode=36622&sku=Goodyear7956989182357515')`

**Comment by 766b** [comment]
Given the amount of time passed, it is probably no longer relevant, but the issue should be with provided key, more than likely there's extra character or it's mangled in some form.
